<?php

namespace Nelio_AB_Testing\Recommendation_Engine\Providers\Traffic;

use WP_Error;
use Nelio_AB_Testing_Settings;
use Nelio_AB_Testing\Recommendation_Engine\Content_Traffic;

final class Nelio_AB_Testing_Traffic_Provider implements Traffic_Provider {

	// @Impleents
	public static function is_available() {
		$settings = Nelio_AB_Testing_Settings::instance();
		$ga_data  = $settings->get( 'google_analytics_data' );
		$property = $ga_data['propertyId'];
		return ! empty( $property );
	}

	// @Implements
	public function get_top_pages( $limit = 20 ) {
		$items = $this->get_top_viewed_items();
		if ( is_wp_error( $items ) ) {
			return array();
		}

		$result = array();
		foreach ( $items as $item ) {
			if ( 'post' !== $item['type'] ) {
				continue;
			}

			if ( ! $item['postType'] || ! $item['postId'] || ! $item['monthlyViews'] ) {
				continue;
			}

			$url = get_permalink( $item['postId'] );
			if ( ! $url ) {
				continue;
			}

			$result[] = new Content_Traffic(
				$item['postType'],
				$item['postId'],
				$url,
				$item['monthlyViews']
			);

			if ( count( $result ) >= $limit ) {
				break;
			}
		}

		return $result;
	}

	/**
	 * Retursn top viewed items.
	 *
	 * @return (
	 *    list< array{type:'url',url:string,monthlyViews:int} | array{type:'post',postId:int,postType:string,monthlyViews:int} > |
	 *    WP_Error
	 * )
	 */
	public function get_top_viewed_items() {
		$data = $this->get_google_analytics_data();
		if ( is_wp_error( $data ) ) {
			return $data;
		}

		return array_map( fn( $row ) => $this->process_ga_row( $row ), $data );
	}

	/**
	 * Returns Google Analytics data.
	 *
	 * @return list<array<string,mixed>>|WP_Error
	 */
	private function get_google_analytics_data() {
		$settings = Nelio_AB_Testing_Settings::instance();
		$ga_data  = $settings->get( 'google_analytics_data' );
		$property = $ga_data['propertyId'];
		if ( empty( $property ) ) {
			return array();
		}

		$params = array( 'propertyId' => $property );
		$body   = wp_json_encode( $params );
		assert( ! empty( $body ) );

		$data = array(
			'method'    => 'POST',
			'timeout'   => absint( apply_filters( 'nab_request_timeout', 60 ) ),
			'sslverify' => ! nab_does_api_use_proxy(),
			'headers'   => array(
				'Authorization' => 'Bearer ' . nab_generate_api_auth_token(),
				'accept'        => 'application/json',
				'content-type'  => 'application/json',
			),
			'body'      => $body,
		);

		$url = add_query_arg(
			'siteId',
			nab_get_site_id(),
			nab_get_api_url( '/ga4/report', 'wp' )
		);

		$response = wp_remote_request( $url, $data );
		$result   = nab_extract_response_body( $response );
		if ( is_wp_error( $result ) ) {
			return new WP_Error( 'nelio-ai-error-913', $result->get_error_code() . ' ' . $result->get_error_message() );
		}

		$result = is_array( $result ) ? $result : array();
		/** @var list<array<string,mixed>> */
		return $result;
	}

	/**
	 * Converts GA Row.
	 *
	 * @param array<string,mixed> $row Data row.
	 *
	 * @return (
	 *    array{type:'url',url:string,monthlyViews:int} |
	 *    array{type:'post',postId:int,postType:string,monthlyViews:int}
	 * )
	 */
	private function process_ga_row( $row ) {
		$path  = $row['path'] ?? '';
		$path  = is_string( $path ) ? $path : '';
		$views = absint( $row['views'] ?? 0 );

		/**
		 * Filters the URL used in GA4 reports.
		 *
		 * @param string $url  The URL generated by combining `home_url` and `path`.
		 * @param string $path The path as reported by GA4.
		 *
		 * @since 8.0.0
		 */
		$url     = apply_filters( 'nab_ai_item_url', home_url( $path ), $path );
		$post_id = nab_url_to_postid( $url );
		if ( ! $post_id ) {
			return array(
				'type'         => 'url',
				'url'          => $url,
				'monthlyViews' => $views,
			);
		}

		$post_type = get_post_type( $post_id );
		$post_type = is_string( $post_type ) ? $post_type : '';
		return array(
			'type'         => 'post',
			'postId'       => $post_id,
			'postType'     => $post_type,
			'monthlyViews' => $views,
		);
	}
}
